### ISSUE TITLE
PDB cannot be read if chain contains only small molecule 

### ISSUE THREAD

**Issue by padix-key** [bjornwallner/DockQ#43] opened 2024-07-22 08:55 UTC
When I read the following PDB file, the following exception is raised:
[sample.pdb.zip](https://github.com/user-attachments/files/16330534/sample.pdb.zip)

```
Traceback (most recent call last):
  File "/Users/kunzmann/Documents/coding/DockQ/src/DockQ/DockQ.py", line 684, in load_PDB
    model = pdb_parser.get_structure(
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kunzmann/Documents/coding/DockQ/src/DockQ/parsers.py", line 297, in get_structure
    chain.sequence = sequences[chain.id]
                     ~~~~~~~~~^^^^^^^^^^
KeyError: 'L'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kunzmann/conda/envs/dockq/lib/python3.12/site-packages/Bio/File.py", line 72, in as_handle
    with open(handleish, mode, **kwargs) as fp:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not TextIOWrapper

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kunzmann/Documents/coding/geotite/../playground/dockq_bug.py", line 3, in <module>
    load_PDB("sample.pdb", small_molecule=True)
  File "/Users/kunzmann/Documents/coding/DockQ/src/DockQ/DockQ.py", line 693, in load_PDB
    model = pdb_parser.get_structure(
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kunzmann/Documents/coding/DockQ/src/DockQ/parsers.py", line 35, in get_structure
    self._mmcif_dict = MMCIF2Dict(filename)
                       ^^^^^^^^^^^^^^^^^^^^
  File "/Users/kunzmann/conda/envs/dockq/lib/python3.12/site-packages/Bio/PDB/MMCIF2Dict.py", line 35, in __init__
    raise ValueError(
ValueError: The input mmCIF file must begin with a 'data_' directive.
```

This Problem only occurs, when the small molecule chain only contains the single small molecule.

**Comment by clami66** [comment] 2024-08-08 09:55
Hi, this should be fixed now. Please update DockQ and see if the issue is solved for your case.

**Closed** 2024-08-27 08:26 UTC
